modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0"

[[mixins]]
config = "townstead.mixins.json"

[[mods]]
modId = "townstead"
version = "${version}"
displayName = "Townstead"
authors = "AetherianArtificer"
description = '''An unofficial expansion for MCA Reborn with additional villager needs, buildings, jobs, and mod integrations.'''
logoFile = "townstead-title-hd.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/townstead"

[modproperties.townstead]
catalogueImageIcon = "townstead-title-square-hd.png"

[[dependencies.townstead]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.townstead]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.townstead]]
modId = "mca"
type = "required"
versionRange = "[7.7.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.townstead]]
modId = "patchouli"
type = "required"
versionRange = "[1.21.1-93,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.townstead]]
modId = "travelerstitles"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.townstead]]
modId = "butchery"
type = "optional"
versionRange = "[4.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.townstead]]
modId = "emotecraft"
type = "optional"
versionRange = "[2.4.12,)"
ordering = "NONE"
side = "CLIENT"
