package com.aetherianartificer.townstead.pheno.lang.schema;

import com.aetherianartificer.townstead.origin.gene.GeneTypes;
import com.aetherianartificer.townstead.pheno.action.ActionTypes;
import com.aetherianartificer.townstead.pheno.action.block.BlockActionTypes;
import com.aetherianartificer.townstead.pheno.action.item.ItemActionTypes;
import com.aetherianartificer.townstead.pheno.condition.ConditionTypes;
import com.aetherianartificer.townstead.pheno.condition.bientity.BiEntityConditionTypes;
import com.aetherianartificer.townstead.pheno.lang.PhenoVersion;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Generates the type manifest, Markdown reference, and JSON Schema from the live registries and
 * {@link NodeSchemas}, so authoring docs and the offline linter cannot drift from what is
 * actually registered. Written to disk by {@code /pheno dump}.
 */
public final class SchemaGen {

    private SchemaGen() {}

    /** Machine-readable list of every registered type by domain, plus the documented schemas. */
    public static JsonObject manifest() {
        JsonObject root = new JsonObject();
        root.addProperty("language_version", PhenoVersion.LATEST.number());
        JsonObject domains = new JsonObject();
        domains.add("gene", sortedKeys(GeneTypes.all().keySet()));
        domains.add("action", sortedKeys(ActionTypes.all().keySet()));
        domains.add("condition", sortedKeys(ConditionTypes.all().keySet()));
        domains.add("bientity_condition", sortedKeys(BiEntityConditionTypes.all().keySet()));
        domains.add("block_action", sortedKeys(BlockActionTypes.all().keySet()));
        domains.add("item_action", sortedKeys(ItemActionTypes.all().keySet()));
        root.add("domains", domains);
        JsonArray schemas = new JsonArray();
        for (NodeSchema schema : NodeSchemas.all()) {
            schemas.add(schemaJson(schema));
        }
        root.add("schemas", schemas);
        return root;
    }

    private static JsonObject schemaJson(NodeSchema schema) {
        JsonObject out = new JsonObject();
        out.addProperty("type", schema.typeKey());
        out.addProperty("domain", schema.domain().name().toLowerCase());
        if (schema.primaryChild() != null) out.addProperty("primary_child", schema.primaryChild());
        if (schema.doc() != null) out.addProperty("doc", schema.doc());
        out.addProperty("side", schema.side().name().toLowerCase());
        JsonArray fields = new JsonArray();
        for (FieldSchema field : schema.fields()) {
            JsonObject f = new JsonObject();
            f.addProperty("name", field.name());
            f.addProperty("kind", field.type().name().toLowerCase());
            f.addProperty("required", field.required());
            if (field.list()) f.addProperty("list", true);
            if (!field.aliases().isEmpty()) f.add("aliases", sortedKeys(field.aliases()));
            if (field.deprecated() != null) f.addProperty("deprecated", field.deprecated());
            if (field.doc() != null) f.addProperty("doc", field.doc());
            fields.add(f);
        }
        out.add("fields", fields);
        return out;
    }

    /** Human-readable reference grouped by domain, generated from the schemas + registry keys. */
    public static String markdown() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Pheno type reference (generated)\n\n");
        sb.append("Language version ").append(PhenoVersion.LATEST.number())
                .append(". Generated by `/pheno dump`; do not edit by hand.\n\n");

        sb.append("## Documented types\n\n");
        for (NodeSchema schema : NodeSchemas.all()) {
            sb.append("### `").append(schema.typeKey()).append("` (")
                    .append(schema.domain().name().toLowerCase()).append(")\n\n");
            if (schema.doc() != null) sb.append(schema.doc()).append("\n\n");
            if (!schema.fields().isEmpty()) {
                sb.append("| field | type | required | notes |\n|---|---|---|---|\n");
                for (FieldSchema f : schema.fields()) {
                    sb.append("| `").append(f.name()).append('`');
                    if (!f.aliases().isEmpty()) sb.append(" (aka ").append(String.join(", ", f.aliases())).append(')');
                    sb.append(" | ").append(f.type().name().toLowerCase()).append(f.list() ? " (list)" : "");
                    sb.append(" | ").append(f.required() ? "yes" : "no");
                    sb.append(" | ").append(f.doc() == null ? "" : f.doc());
                    if (f.deprecated() != null) sb.append(" deprecated: ").append(f.deprecated());
                    sb.append(" |\n");
                }
                sb.append('\n');
            }
        }

        sb.append("## All registered types\n\n");
        appendKeyList(sb, "Genes", GeneTypes.all().keySet());
        appendKeyList(sb, "Actions", ActionTypes.all().keySet());
        appendKeyList(sb, "Conditions", ConditionTypes.all().keySet());
        appendKeyList(sb, "Bi-entity conditions", BiEntityConditionTypes.all().keySet());
        appendKeyList(sb, "Block actions", BlockActionTypes.all().keySet());
        appendKeyList(sb, "Item actions", ItemActionTypes.all().keySet());
        return sb.toString();
    }

    /** A pragmatic JSON Schema for gene files: validates the top-level type and version. */
    public static JsonObject jsonSchema() {
        JsonObject root = new JsonObject();
        root.addProperty("$schema", "http://json-schema.org/draft-07/schema#");
        root.addProperty("title", "Townstead Pheno gene");
        root.addProperty("type", "object");
        JsonObject properties = new JsonObject();
        JsonObject version = new JsonObject();
        version.addProperty("type", "integer");
        version.addProperty("minimum", 1);
        properties.add("pheno_version", version);
        JsonObject type = new JsonObject();
        type.add("enum", sortedKeys(GeneTypes.all().keySet()));
        properties.add("type", type);
        root.add("properties", properties);
        return root;
    }

    private static void appendKeyList(StringBuilder sb, String title, Collection<String> keys) {
        sb.append("**").append(title).append("** (").append(keys.size()).append("): ");
        List<String> sorted = new ArrayList<>(keys);
        sorted.sort(String::compareTo);
        sb.append(String.join(", ", sorted)).append("\n\n");
    }

    private static JsonArray sortedKeys(Collection<String> keys) {
        List<String> sorted = new ArrayList<>(keys);
        sorted.sort(String::compareTo);
        JsonArray arr = new JsonArray();
        for (String k : sorted) arr.add(k);
        return arr;
    }
}
