package com.aetherianartificer.townstead.origin.ability;

import com.aetherianartificer.townstead.origin.gene.Gene;
import com.aetherianartificer.townstead.origin.gene.GeneRegistry;
import com.aetherianartificer.townstead.origin.gene.types.ReachHook;
import com.aetherianartificer.townstead.origin.gene.types.ResourceGeneType;
import com.aetherianartificer.townstead.pheno.action.ActionContext;
import com.aetherianartificer.townstead.pheno.power.Power;
import com.aetherianartificer.townstead.pheno.power.Powers;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.LivingEntity;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Per-entity values for {@code resource} genes (transient; reset on reload, like
 * cooldowns). Initialised to the gene's start value on first access, regenerated by
 * the passive tick, spent by active abilities, and moved by the {@code change_resource}
 * action.
 */
public final class ResourceValues {

    private static final Map<UUID, Map<ResourceLocation, Integer>> VALUES = new ConcurrentHashMap<>();

    private ResourceValues() {}

    public static int get(LivingEntity entity, ResourceLocation geneId) {
        Map<ResourceLocation, Integer> map = VALUES.get(entity.getUUID());
        if (map != null && map.containsKey(geneId)) return map.get(geneId);
        ResourceGeneType.Instance instance = instanceOf(geneId);
        return instance == null ? 0 : instance.start();
    }

    /** Move a resource by {@code delta}, clamped to the gene's range. */
    public static void change(LivingEntity entity, ResourceLocation geneId, int delta) {
        ResourceGeneType.Instance instance = instanceOf(geneId);
        if (instance == null) return;
        set(entity, geneId, get(entity, geneId) + delta);
    }

    /** Set a resource to {@code value}, clamped to the gene's range (Apoli's {@code operation:"set"}). */
    public static void set(LivingEntity entity, ResourceLocation geneId, int value) {
        ResourceGeneType.Instance instance = instanceOf(geneId);
        if (instance == null) return;
        int prev = get(entity, geneId);
        int next = Math.max(instance.min(), Math.min(instance.max(), value));
        VALUES.computeIfAbsent(entity.getUUID(), k -> new ConcurrentHashMap<>()).put(geneId, next);
        if (next > prev && !instance.onReach().isEmpty()) fireReach(entity, geneId, instance, prev, next);
    }

    /** Fire any on_reach hook the rise from {@code prev} to {@code next} crosses; reset the meter if asked. */
    private static void fireReach(LivingEntity entity, ResourceLocation geneId,
                                  ResourceGeneType.Instance instance, int prev, int next) {
        boolean reset = false;
        for (ReachHook hook : instance.onReach()) {
            if (!hook.crossed(prev, next)) continue;
            hook.action().run(new ActionContext(entity));
            if (hook.reset()) reset = true;
        }
        if (reset) {
            int start = Math.max(instance.min(), Math.min(instance.max(), instance.start()));
            VALUES.computeIfAbsent(entity.getUUID(), k -> new ConcurrentHashMap<>()).put(geneId, start);
        }
    }

    /** Regenerate every expressed resource gene on its own interval. */
    public static void tick(LivingEntity entity) {
        for (Power gene : Powers.active(entity)) {
            if (!(gene.component() instanceof ResourceGeneType.Instance instance)) continue;
            if (instance.regen() == 0 || entity.tickCount % instance.regenInterval() != 0) continue;
            change(entity, gene.id(), instance.regen());
        }
    }

    /** Send the player their resource snapshot for the HUD (throttled; player-only). */
    public static void syncTo(ServerPlayer player) {
        if (player.tickCount % 5 != 0) return;
        List<ResourceSyncS2CPayload.Bar> bars = new ArrayList<>();
        for (Power gene : Powers.active(player)) {
            if (gene.component() instanceof ResourceGeneType.Instance instance) {
                bars.add(new ResourceSyncS2CPayload.Bar(
                        gene.id().toString(), get(player, gene.id()), instance.max(), instance.color()));
            }
        }
        ResourceSyncS2CPayload payload = new ResourceSyncS2CPayload(bars);
        //? if neoforge {
        net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(player, payload);
        //?} else {
        /*com.aetherianartificer.townstead.TownsteadNetwork.sendToPlayer(player, payload);
        *///?}
    }

    public static void clear(UUID uuid) {
        VALUES.remove(uuid);
    }

    private static ResourceGeneType.Instance instanceOf(ResourceLocation geneId) {
        Gene gene = GeneRegistry.byId(geneId);
        return gene != null && gene.instance() instanceof ResourceGeneType.Instance instance ? instance : null;
    }
}
